name: python35
dependencies:
- appnope=0.1.0=py35_0
- astropy=1.2.1=np111py35_0
- backports=1.0=py35_0
- boto=2.40.0=py35_0
- ca-certificates=2016.2.28=0
- certifi=2016.2.28=py35_1
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- freetype=2.6.3=1
- get_terminal_size=1.0.0=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_1
- ipython-notebook=4.0.4=py35_0
- ipython_genutils=0.1.0=py35_0
- jinja2=2.8=py35_1
- jplephem=2.5=py35_0
- jsonschema=2.5.1=py35_0
- jupyter_client=4.3.0=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.23=0
- llvmlite=0.12.1=py35_0
- markupsafe=0.23=py35_2
- matplotlib=1.5.2=np111py35_4
- mistune=0.7.2=py35_1
- mkl=11.3.3=0
- mpmath=0.19=py35_1
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.2.1=py35_0
- numba=0.27.0=np111py35_0
- numpy=1.11.1=py35_0
- openssl=1.0.2h=2
- pandas=0.18.1=np111py35_0
- path.py=8.2.1=py35_0
- pcre=8.39=0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.2=py35_0
- pip=8.1.2=py35_0
- poliastro=0.5.0=py35_0
- ptyprocess=0.5.1=py35_0
- py=1.4.31=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_3
- pytest=2.9.2=py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- python.app=1.2=py35_4
- pytz=2016.6.1=py35_0
- pyzmq=15.2.0=py35_1
- qt=4.8.7=3
- readline=6.2=2
- scipy=0.18.0=np111py35_0
- setuptools=26.1.1=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- swig=3.0.8=1
- sympy=1.0=py35_0
- terminado=0.6=py35_0
- tk=8.5.18=0
- tornado=4.3=py35_1
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xlrd=1.0.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-core==4.1.0
  - plotly==1.12.2
  - requests==2.10.0
  - spiceypy==1.0.0

